[package]
name = "exercise"
version = "0.1.0"
edition = "2021"
publish = ["artifactory"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "5_6"
path = "src/5_6.rs"

[[bin]]
name = "6_3_1"
path = "src/6_3_1.rs"

[dependencies]
